// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("dotenv");
var Process = require("process");
var Js_option = require("bs-platform/lib/js/js_option.js");
var MnstrUtils = require("@ecliptic/mnstr/src/MnstrUtils.bs.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var ParseDatabaseUrl = require("parse-database-url");

Dotenv.config({
      silent: /* true */1
    });

function getEnvVar(key, fallback) {
  return Js_option.getWithDefault(fallback, Js_primitive.undefined_to_opt(Process.env[key]));
}

var url = getEnvVar("DATABASE_URL", "postgres://trailmap:trailmap@localhost:5432/trailmap");

var config = ParseDatabaseUrl(url);

var name = config.database;

var username = config.user;

var password = config.password;

var hostname = config.host;

var hosts = config.hosts;

var port = config.port;

var poolMin = MnstrUtils.Text[/* parseInt */0](getEnvVar("DATABASE_POOL_MIN", "0"));

var poolMax = MnstrUtils.Text[/* parseInt */0](getEnvVar("DATABASE_POOL_MAX", "10"));

var poolIdle = MnstrUtils.Text[/* parseInt */0](getEnvVar("DATABASE_POOL_IDLE", "10000"));

var Database = /* module */[
  /* url */url,
  /* config */config,
  /* name */name,
  /* username */username,
  /* password */password,
  /* hostname */hostname,
  /* hosts */hosts,
  /* port */port,
  /* poolMin */poolMin,
  /* poolMax */poolMax,
  /* poolIdle */poolIdle
];

var port$1 = MnstrUtils.Text[/* parseInt */0](getEnvVar("PORT", "4000"));

var corsHeaders = /* array */["Link"];

var isDev = +(getEnvVar("NODE_ENV", "production") === "development");

var Server = /* module */[
  /* port */port$1,
  /* bodyLimit */"100kb",
  /* corsHeaders */corsHeaders,
  /* isDev */isDev
];

exports.getEnvVar = getEnvVar;
exports.Database = Database;
exports.Server = Server;
/*  Not a pure module */
